### PR TITLE
[Paper+1] Probabilistic Programming and PyMC3, Peadar Coyle

### PR DESCRIPTION
**Pull request by springcoil**
My submission of my paper.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
After an initial review of the paper here are some comments. I hope they are helpful.

Line 41: single sentences are not paragraphs. The introduction section is not very coherent, and is just a selection of rugby facts. For example, I'm not sure why the average player information is relevant. I recommend reworking the introduction to make it more readable, and better introduce the subject. 

Line 41: The tilde `~` symbol is more conventional as a symbol for "distributed as" than an equal sign; its not clear why you would choose an unconventional symbol.

Line 44: not sure what "there is no need of the bivariate Poisson modelling." means. Please clarify.

Line 44: replace "We use here the result proved in" with "Here, we present the results shown by"

Line 44: I don't think this exposition will be clear for someone who is not very familiar with hierarchical models.

Line 44: Suggest changing "Moreover, as we are framed in a Bayesian context, prediction of a new game under the model is naturally accommodated by means the posterior predictive distribution." to "Moreover, since we are employing a Bayesian framework, the prediction of the outcome of a new game under the model is provided by the posterior predictive distribution."

Line 51: Since you are the only author, should be "My model"

Line 51: These sentence are non-coherent, and sections appear to be missing; please edit.

Line 56: "Let me introduce"

Line 110: Place "home" in inline code block. Same goes for all Python variables in the text. This makes it easier to read and follow.

Line 110: These three sentences should be combined into a paragraph. Avoid one-line paragraphs.

Line 131: Suggested re-wording: "Team strength is decomposed into attacking and defending strength components."

Line 139: Merge with line above into single paragraph.

Line 170: These three lines should be merged into a single paragraph and made more coherent. You say "important things", but then mention only one thing.

Line 179: Change "From the above we can start to understand" to "We can use the model above to help us estimate"

Line 189: Change "Here we in :ref:`egfig` can see an example of the figures you can generate, we are looking at the credibility intervals" into ":ref:`egfig` is an example of the type of figures that can be generated, which in this example is a forest plot of credible intervals."

Line 190: Change "The list of teams is" to "the estimated rankings of teams is"

Line 192: This paragraph is not very coherent. I suggest revising it, simplifying to include the major take-home message(s) of the paper.

**Comment by springcoil** [comment]
Hi Chris, I'll implement these changes soon

**Comment by springcoil** [comment]
Ok I made those changes - let me know your view @fonnesbeck

**Comment by fonnesbeck** [comment]
@springcoil These changes look good to me. No further suggestions or edits.

**Comment by springcoil** [comment]
Let me know @NelleV when this gets merged :)

**Pull request merged**
