### PR TITLE
[Paper+1] Want drugs? Use Python. M. Nowotka

### PR DESCRIPTION
**Pull request by mnowotka**

### CODE REVIEW

**Comment by FedericoV** [comment]
Overall comments: it's a great resource, with excellent tutorials and lots of examples.  The paper is well written as well.

The only thing which is missing and I'd love to see is a big conda meta-package to install all the complex packages and their dependencies - which is slightly less cumbersome to use than a full virtual machine or docker image.

**Comment by mnowotka** [comment]
Hi @FedericoV,
Thank you for your comments. For the next myChEMBL release we are planning to replace virtualenv with miniconda. I think this will be a good start to implement your idea, which is very good and can further streamline the whole process. I'll apply all the stylistic changes, you've suggested, later today.

**Comment by FedericoV** [comment]
Hi Michal,

I'm not an expert at commenting directly on github diffs - I'll go through
the paper in more detail during the week-end.  A lot of the work is in the
(excellent) examples that you link - so this paper I guess serves more to
present everything done by the chEMBL group as a coherent whole?

**Comment by mnowotka** [comment]
Yes, this paper was meant to provide a high-level picture of all ChEMBL activities, where Python plays an important role. So far your comments made on diffs are clear for me. Take your time to correct the paper and let me know when you are done so I will apply all the changes in one go.

**Comment by FedericoV** [comment]
I've been going through the examples.  Most are very good - but in some cases you are duplicating existing functionality that can be covered with other excellent libraries.  For example, lots of the demo plots in the plotting tutorial can be done with two lines using seaborn.

The molecule plots in iPython using the display hooks are very impressive though.

**Comment by FedericoV** [comment]
Anyway - I think the paper is well written, and the documentation and notebooks are excellent.  I wish there was a conda package to deal with the build headache instead of a virtual machine, but I understand that's on the TODO list for your group as well.

**Comment by mnowotka** [comment]
Hi @FedericoV - I'd like to include seaborn in our software stack to reduce functionality duplication. Can you give a couple of examples of replacing our demo plots with seaborn?

Also, are there any other libraries that can help us to avoid reinventing the wheel? I'd be happy to use as many well-know good-quality libraries as possible if they make common tasks much simpler, as long as those libraries are open source.

**Pull request merged**
