### PR TITLE
[Paper+2] Using the IPython Notebook as Lab Notebook

### PR DESCRIPTION
**Pull request by juhasch**

### CODE REVIEW

**Comment by Carreau** [comment]
I'm really happy to see that, it is a nice showcase on how you can extend the notebook, and I know that @juhasch have spend a lot of time writing extensions and made them available to user. 

The `‘ 20 m / 15 s‘` seem to be badly rendered.

In figure 2, if you wish you can describe what can be seen/not seen on the picture which is due to extension (button in the toolbar, code cell hidden ?). 

Figure 3, you could add in the description, something like "`StatelessInputTransformer` allow non python syntax like `10 um`" which emphasize what you have done.


These are just suggestion. Good job otherwise !

**Comment by khinsen** [comment]
In reply to the invitation to review this paper: I accept, but I can start only in about a week.

**Comment by khinsen** [comment]
Here are my first impressions.

What this paper requires most of all is a clearer focus. What's the intended message? It reads a bit like "some things you can do with IPython notebooks". Given that the IPython notebook is already quite popular, it is not obvious what the intention of the author is. A big part of the article is about extensions, so perhaps that should become the focus.

On a related note, the title and introduction suggest a comparison to traditional lab notebooks. However, that is not the role that the IPython notebook has in most scientists' workflows, and it is not even particularly well suited to this task. An IPython notebook is more a scratchpad for developing ideas than a lab notebook.

As a reminder, a lab notebook is used for keeping time-stamped notes of what was done. It's a bit like a bank ledger: you append at the end, but never change what was written earlier. The closest equivalent we have in the digital world is certain version control systems such as Mercurial or subversion. Even git doesn't fully qualify because it encourages rewriting history. The IPython notebook doesn't integrate well with version control, as the article mentions, so it seems strange to see the reference to lab notebooks at all.

Section 2 contains mostly unqualified judgements. I'd expect a more rigorous approach in a scientific environment. What exactly is shocking about the use of MS Word? In what way is Mathematica less easy to use than Python? Easy for who? BTW, none of the tools in section 2 fulfills the role of a lab notebook.

**Comment by NelleV** [comment]
I going to have decline this paper, as the reviewers' comment were not addressed.

**Pull request closed without merging**
